## RGrowthCurves 
## This is the script helping to calculate yeast growth rate, duplication time, 
## lag period from csv file generated by multi-well spectrophotometer


# Set working directory 
# IMPORTANT 5 min increment
setwd("/home/dima/Desktop/R")
library(lme4)

# Write headings to output file
ColNamesOut <- paste("conditions", "Mu","tau12, h", "starting OD", "OD10h", "OD10h_1", "lag, min", "r2", sep = ";")
write (ColNamesOut, file = "tidy_output.txt", append = TRUE)

# Read table - CHECK SEPARATORS!
inn <- read.table("in.csv",header=head, sep =";")

# IMPORTANT! Add time scale default 5 min
incubation_time <-length(input_data[,1])
time <-5*c(0:(incubation_time-1)) # set time scale here

# Merging data & calculated log OD
inn <-cbind(time,input_data)
innlog2 <- log2(inn)

# Calculate table dimension
col_number <- length(inn)
row_number <-nrow(inn)

# Define window
window <- 50

# Main cycle
for(i in c(2:col_number))

{

#Plot log
exper <-i         # set the column (experiment) number 
experTitle <-colnames(inn[exper])

#find maximum slope
max_slope <- 0
lag <-0
r2fit <-0 

x_scale <- c()
slopes <- c()
rs <-c()

for(i in c(20:(row_number-window))) # set first point for fit

{FIT <- lm(innlog2[i:(i+50),exper] ~ inn[i:(i+50),1])
r2fit <- summary(FIT)$r.squared

x_scale <-c(x_scale,i)
slopes <-c(slopes,0.693147181*(60*coef(FIT)[2]))
rs <-c(rs,r2fit)

    if (coef(FIT)[2] > max_slope) {
                max_slope <- coef(FIT)[2]
                lag <- i
#                print('updated')
#                print(i)
                FINALFIT <- FIT
                finalR2 <- r2fit
                }
}

print(FINALFIT)
print(finalR2)

#PLOTTING DATA

filename <- paste("00",exper,"_",substr(experTitle,0,4),".jpg",sep="")
jpeg(filename = filename)

mu_for_figure = 0.693147181*(60*coef(FINALFIT)[2]) 
mu_for_figure = substr(as.character(mu_for_figure), 1,5)


plot(inn[,1],innlog2[,exper], ylim = c(-4,2), main=experTitle,col = 'blue')
points(inn[,1],inn[,exper], ylim = c(-4,2))
points(x_scale*5, 10*slopes-4, col = 'green')
points(x_scale*5, rs, col = "orange")
abline(FINALFIT,col = 'red')
abline (v = lag*5, col = 'blue')
text(100,1.5,expression(mu*" ="), pos= 2, col = "red", cex = 1.5) 
text(100,1.5,mu_for_figure, pos= 4, col = "red",cex = 1.5) 
dev.off()

# print experiment name, slope and intercept coeficients
print(experTitle)
print(1/(60*coef(FINALFIT)[2]))
print (FINALFIT)[1]

# write to file experiment name, tau 1/2 and intercept coeficients
mu <- paste(experTitle, 0.693147181*(60*coef(FINALFIT)[2]),sep = ';')

# write to file experiment name, tau 1/2 and intercept coeficients
tau12 <- 1/(60*coef(FINALFIT)[2])

#write OD 10 hours
OD <- mean(inn[126:138,exper]-mean(inn[6:18,exper]))
OD1 <- mean((inn[126:138,exper]))  #without substraction of 0D = 0
starting_OD <- mean(inn[2:8,exper])


tidy_output <- paste(mu, tau12, starting_OD, OD, OD1, lag*5, finalR2, sep = ";")
write (tidy_output, file = "tidy_output.txt", append = TRUE)

}


