## RGrowthCurves 
## This script calculates yeast growth rate, duplication time and 
## lag period 
## It takes csv file generated by multi-well spectrophotometer 
## Version 0.3.1

# Set working directory 
# IMPORTANT 5 min increment
setwd("/home/dima/Desktop/R")
library(lme4)
library(Matrix)
version = "0.3.1"

# Write headings to output file
ColNamesOut <- paste("conditions", 
                     "Mu",
                     "tau12, h", 
                     "starting OD", 
                     "OD10h_minusStartingOD", 
                     "OD10h_abs", 
                     "lag, min", 
                     "lag_corrected, min",
                     "r2", 
                     "RGScript_version", 
                     "Mu_10",
                     "Mu_12",
                     "Mu_14",
                     sep = ";")

write (ColNamesOut, file = "tidy_output.txt", append = TRUE)

# Read table - CHECK SEPARATORS!
inn <- read.table("in.csv", header=TRUE, sep =";")

# IMPORTANT! Add time scale default 5 min
incubation_time <-length(inn[,1])
time <-5*c(0:(incubation_time-1)) # set time scale here

# Merging data & calculated log OD
inn <- cbind(time, inn)
innlog2 <- log2(inn)

# Calculate table dimension
col_number <- length(inn)
row_number <- nrow(inn)

# Define window
window <- 50

# Main cycle
for(experiment in c(2:col_number))

{

#Plot log
exper <- experiment         # set the column (experiment) number 
experTitle <-colnames(inn[exper])

#find maximum slope
max_slope <- 0
lag <-0
r2fit <-0 
# some experiments vary in length, therefore to standartize
# calculation output we calculate mu for different time scales
max_slope_10 <- 0
max_slope_12 <- 0
max_slope_14 <- 0


x_scale <- c()
slopes <- c()
rs <-c()

for(i in c(20:(row_number-window))) # set first point for fit
    {
    FIT <- lm(innlog2[i:(i+window),exper] ~ inn[i:(i+window),1])
    r2fit <- summary(FIT)$r.squared
    x_scale <-c(x_scale, i)
    slopes <-c(slopes, 0.693147181*(60*coef(FIT)[2]))
    rs <-c(rs, r2fit)

    if (coef(FIT)[2] > max_slope) {
                max_slope <- coef(FIT)[2]
                intercept <- coef(FIT)[1]
                lag <- i
                FINALFIT <- FIT
                final_intercept <- intercept
                finalR2 <- r2fit
    }
    
    if (i*5 == 600) {max_slope_10 <- max_slope}
    if (i*5 == 720) {max_slope_12 <- max_slope}
    if (i*5 == 840) {max_slope_14 <- max_slope}
    
}


### Calculate auxiliary parameters
OD <- mean(inn[126:138,exper]-mean(inn[6:18,exper]))
OD1 <- mean((inn[126:138,exper]))  #without substraction of 0D = 0
starting_OD <- mean(inn[2:8,exper])
lag_corrected <- (log2(starting_OD)-final_intercept)/max_slope

# write to file experiment name, tau 1/2 and intercept coeficients
mu <- paste(experTitle, 0.693147181*(60*coef(FINALFIT)[2]),sep = ';')
mu_10 <- 0.693147181*60*max_slope_10[[1]]
mu_12 <- 0.693147181*60*max_slope_12[[1]]
mu_14 <- 0.693147181*60*max_slope_14[[1]]
# write to file experiment name, tau 1/2 and intercept coeficients
tau12 <- 1/(60*coef(FINALFIT)[2])

#PLOTTING DATA

filename <- paste("00",exper,"_",substr(experTitle,0,4),".jpg",sep="")
jpeg(filename = filename)

mu_for_figure = 0.693147181*(60*coef(FINALFIT)[2]) 
mu_for_figure = substr(as.character(mu_for_figure), 1,5)
plot(inn[,1],
     innlog2[,exper], 
     ylim = c(-4,2), 
     main=experTitle,col = 'blue',
     xlab="Time, min", 
     ylab="OD or log2(OD)")
points(inn[,1],inn[,exper], ylim = c(-4,2))
points(x_scale*5, 10*slopes-4, col = 'green')
points(x_scale*5, rs, col = "orange")
abline(FINALFIT,col = 'red')
abline (v = lag*5, col = 'blue')
abline(h = log2(starting_OD), lty = 2, col = 'darkgreen')
text(100,1.5,expression(mu*" ="), pos= 2, col = "red", cex = 1.5) 
text(100,1.5,mu_for_figure, pos= 4, col = "red",cex = 1.5) 
points(lag_corrected, log2(starting_OD), col = 'red', cex = 1.5, pch = 19)
dev.off()

# print experiment name, slope and intercept coeficients
print(experTitle)
print(1/(60*coef(FINALFIT)[2]))
print (FINALFIT)[1]


###### Prepare data to csv row
tidy_output <- paste(mu, 
                     tau12, 
                     starting_OD, 
                     OD, 
                     OD1, 
                     lag*5, 
                     lag_corrected,
                     finalR2, 
                     version, 
                     mu_10,
                     mu_12,
                     mu_14,
                     sep = ";")
write (tidy_output, file = "tidy_output.txt", append = TRUE)
}
